
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Rain.Config
{
/// <summary>
/// 设置
/// </summary>
public partial class GameSettingTable
{
    private readonly System.Collections.Generic.Dictionary<string, GameSettingConfig> _dataMap;
    private readonly System.Collections.Generic.List<GameSettingConfig> _dataList;
    
    public GameSettingTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, GameSettingConfig>();
        _dataList = new System.Collections.Generic.List<GameSettingConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            GameSettingConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Rain.Config.GameSettingConfig.DeserializeGameSettingConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, GameSettingConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<GameSettingConfig> DataList => _dataList;

    public GameSettingConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameSettingConfig Get(string key) => _dataMap[key];
    public GameSettingConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

