
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Rain.Config
{
/// <summary>
/// 图文混合
/// </summary>
public partial class ImageTextMixTable
{
    private readonly System.Collections.Generic.Dictionary<string, ImageTextMixConfig> _dataMap;
    private readonly System.Collections.Generic.List<ImageTextMixConfig> _dataList;
    
    public ImageTextMixTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, ImageTextMixConfig>();
        _dataList = new System.Collections.Generic.List<ImageTextMixConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ImageTextMixConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Rain.Config.ImageTextMixConfig.DeserializeImageTextMixConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Tid, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, ImageTextMixConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<ImageTextMixConfig> DataList => _dataList;

    public ImageTextMixConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ImageTextMixConfig Get(string key) => _dataMap[key];
    public ImageTextMixConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

