
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Rain.Config
{
public sealed partial class SLGSettingConfig : Luban.BeanBase
{
    public SLGSettingConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["val"].IsString) { throw new SerializationException(); }  Val = _buf["val"]; }
        { if(!_buf["RTSVal"].IsString) { throw new SerializationException(); }  RTSVal = _buf["RTSVal"]; }
    }

    public static SLGSettingConfig DeserializeSLGSettingConfig(JSONNode _buf)
    {
        return new SLGSettingConfig(_buf);
    }

    public readonly string ID;
    public readonly string Val;
    public readonly string RTSVal;
   
    public const int __ID__ = 780408644;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "val:" + Val + ","
        + "RTSVal:" + RTSVal + ","
        + "}";
    }
}
}

