
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Rain.Config
{
/// <summary>
/// 设置
/// </summary>
public partial class SLGSettingTable
{
    private readonly System.Collections.Generic.Dictionary<string, SLGSettingConfig> _dataMap;
    private readonly System.Collections.Generic.List<SLGSettingConfig> _dataList;
    
    public SLGSettingTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, SLGSettingConfig>();
        _dataList = new System.Collections.Generic.List<SLGSettingConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            SLGSettingConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Rain.Config.SLGSettingConfig.DeserializeSLGSettingConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, SLGSettingConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<SLGSettingConfig> DataList => _dataList;

    public SLGSettingConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SLGSettingConfig Get(string key) => _dataMap[key];
    public SLGSettingConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

