
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Rain.Config
{
public partial class Tables
{
    /// <summary>
    /// 设置
    /// </summary>
    public GameSettingTable GameSettingTable {get; }
    /// <summary>
    /// 设置
    /// </summary>
    public SLGSettingTable SLGSettingTable {get; }
    /// <summary>
    /// 图文混合
    /// </summary>
    public ImageTextMixTable ImageTextMixTable {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        GameSettingTable = new GameSettingTable(loader("gamesettingtable"));
        SLGSettingTable = new SLGSettingTable(loader("slgsettingtable"));
        ImageTextMixTable = new ImageTextMixTable(loader("imagetextmixtable"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        GameSettingTable.ResolveRef(this);
        SLGSettingTable.ResolveRef(this);
        ImageTextMixTable.ResolveRef(this);
    }
}

}
