
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Rain.Config
{
public sealed partial class ImageTextMixConfig : Luban.BeanBase
{
    public ImageTextMixConfig(JSONNode _buf) 
    {
        { if(!_buf["tid"].IsString) { throw new SerializationException(); }  Tid = _buf["tid"]; }
        { if(!_buf["img_c_1"].IsString) { throw new SerializationException(); }  ImgC1 = _buf["img_c_1"]; }
        { if(!_buf["img_c_2"].IsString) { throw new SerializationException(); }  ImgC2 = _buf["img_c_2"]; }
        { if(!_buf["img_c_3"].IsString) { throw new SerializationException(); }  ImgC3 = _buf["img_c_3"]; }
    }

    public static ImageTextMixConfig DeserializeImageTextMixConfig(JSONNode _buf)
    {
        return new ImageTextMixConfig(_buf);
    }

    /// <summary>
    /// 文本ID
    /// </summary>
    public readonly string Tid;
    /// <summary>
    /// res读取路径,宽,高
    /// </summary>
    public readonly string ImgC1;
    public readonly string ImgC2;
    public readonly string ImgC3;
   
    public const int __ID__ = 1661652118;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "tid:" + Tid + ","
        + "imgC1:" + ImgC1 + ","
        + "imgC2:" + ImgC2 + ","
        + "imgC3:" + ImgC3 + ","
        + "}";
    }
}
}

