
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 设置
/// </summary>
public partial class Setting
{
    private readonly System.Collections.Generic.Dictionary<string, common.GameSetting> _dataMap;
    private readonly System.Collections.Generic.List<common.GameSetting> _dataList;
    
    public Setting(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, common.GameSetting>();
        _dataList = new System.Collections.Generic.List<common.GameSetting>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            common.GameSetting _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.common.GameSetting.DeserializeGameSetting(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, common.GameSetting> DataMap => _dataMap;
    public System.Collections.Generic.List<common.GameSetting> DataList => _dataList;

    public common.GameSetting GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public common.GameSetting Get(string key) => _dataMap[key];
    public common.GameSetting this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

