
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    /// <summary>
    /// 设置
    /// </summary>
    public Setting Setting {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        Setting = new Setting(loader("Setting"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        Setting.ResolveRef(this);
    }
}

}
