
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Rain.Config
{
public partial class Tables
{
    /// <summary>
    /// 设置
    /// </summary>
    public Setting Setting {get; }
    /// <summary>
    /// 设置
    /// </summary>
    public ImageTextMix ImageTextMix {get; }
    /// <summary>
    /// 设置
    /// </summary>
    public Unit Unit {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        Setting = new Setting(loader("setting"));
        ImageTextMix = new ImageTextMix(loader("imagetextmix"));
        Unit = new Unit(loader("unit"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        Setting.ResolveRef(this);
        ImageTextMix.ResolveRef(this);
        Unit.ResolveRef(this);
    }
}

}
