
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Rain.Core
{
public sealed partial class BuildingSlotConfig : Luban.BeanBase
{
    public BuildingSlotConfig(JSONNode _buf) 
    {
        { if(!_buf["SlotID"].IsNumber) { throw new SerializationException(); }  SlotID = _buf["SlotID"]; }
        { if(!_buf["PositionX"].IsNumber) { throw new SerializationException(); }  PositionX = _buf["PositionX"]; }
        { if(!_buf["PositionZ"].IsNumber) { throw new SerializationException(); }  PositionZ = _buf["PositionZ"]; }
        { if(!_buf["RotationY"].IsNumber) { throw new SerializationException(); }  RotationY = _buf["RotationY"]; }
        { if(!_buf["IsLocked"].IsBoolean) { throw new SerializationException(); }  IsLocked = _buf["IsLocked"]; }
        { var __json0 = _buf["UnlockCondition"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockCondition = new System.Collections.Generic.Dictionary<CityBuildingType, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { CityBuildingType _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = (CityBuildingType)__e0[0].AsInt; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  UnlockCondition.Add(_k0, _v0); }   }
    }

    public static BuildingSlotConfig DeserializeBuildingSlotConfig(JSONNode _buf)
    {
        return new BuildingSlotConfig(_buf);
    }

    public readonly int SlotID;
    public readonly int PositionX;
    public readonly int PositionZ;
    public readonly int RotationY;
    public readonly bool IsLocked;
    public readonly System.Collections.Generic.Dictionary<CityBuildingType, int> UnlockCondition;
   
    public const int __ID__ = 2040872148;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "SlotID:" + SlotID + ","
        + "PositionX:" + PositionX + ","
        + "PositionZ:" + PositionZ + ","
        + "RotationY:" + RotationY + ","
        + "IsLocked:" + IsLocked + ","
        + "UnlockCondition:" + Luban.StringUtil.CollectionToString(UnlockCondition) + ","
        + "}";
    }
}
}

