
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Rain.Core
{
public sealed partial class CityBuildingConfig : Luban.BeanBase
{
    public CityBuildingConfig(JSONNode _buf) 
    {
        { if(!_buf["buildingID"].IsNumber) { throw new SerializationException(); }  BuildingID = (CityBuildingType)_buf["buildingID"].AsInt; }
        { if(!_buf["buildingName"].IsString) { throw new SerializationException(); }  BuildingName = _buf["buildingName"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["slot"].IsNumber) { throw new SerializationException(); }  Slot = _buf["slot"]; }
        { if(!_buf["maxLevel"].IsNumber) { throw new SerializationException(); }  MaxLevel = _buf["maxLevel"]; }
        { if(!_buf["BuildingModel"].IsString) { throw new SerializationException(); }  BuildingModel = _buf["BuildingModel"]; }
        { if(!_buf["PlotModel"].IsString) { throw new SerializationException(); }  PlotModel = _buf["PlotModel"]; }
        { if(!_buf["constructionModel"].IsString) { throw new SerializationException(); }  ConstructionModel = _buf["constructionModel"]; }
        { if(!_buf["scale"].IsNumber) { throw new SerializationException(); }  Scale = _buf["scale"]; }
    }

    public static CityBuildingConfig DeserializeCityBuildingConfig(JSONNode _buf)
    {
        return new CityBuildingConfig(_buf);
    }

    public readonly CityBuildingType BuildingID;
    /// <summary>
    /// 建筑名称
    /// </summary>
    public readonly string BuildingName;
    /// <summary>
    /// 图标占位（备用）
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 位置
    /// </summary>
    public readonly int Slot;
    public readonly int MaxLevel;
    /// <summary>
    /// 建筑模型
    /// </summary>
    public readonly string BuildingModel;
    /// <summary>
    /// 空地模型
    /// </summary>
    public readonly string PlotModel;
    /// <summary>
    /// 建造中模型路径
    /// </summary>
    public readonly string ConstructionModel;
    /// <summary>
    /// 缩放
    /// </summary>
    public readonly float Scale;
   
    public const int __ID__ = 215577985;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "buildingID:" + BuildingID + ","
        + "buildingName:" + BuildingName + ","
        + "icon:" + Icon + ","
        + "desc:" + Desc + ","
        + "slot:" + Slot + ","
        + "maxLevel:" + MaxLevel + ","
        + "BuildingModel:" + BuildingModel + ","
        + "PlotModel:" + PlotModel + ","
        + "constructionModel:" + ConstructionModel + ","
        + "scale:" + Scale + ","
        + "}";
    }
}
}

