
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Rain.Core
{ 
    /// <summary>
    /// 城镇建筑类型
    /// </summary>
    public enum CityBuildingType
    {
        /// <summary>
        /// 市政厅
        /// </summary>
        Main = 1,
        /// <summary>
        /// 科研所
        /// </summary>
        Tech = 2,
        /// <summary>
        /// 畜牧场
        /// </summary>
        Farm = 3,
        /// <summary>
        /// 伐木场
        /// </summary>
        Mill = 4,
        /// <summary>
        /// 炼金工房
        /// </summary>
        AlchemicalWorkshop = 5,
        /// <summary>
        /// 手抄工坊
        /// </summary>
        HandwritingWorkshop = 6,
        /// <summary>
        /// 骑士营
        /// </summary>
        CavalryCamp = 7,
        /// <summary>
        /// 靶场
        /// </summary>
        ArcherCamp = 8,
        /// <summary>
        /// 魔法塔
        /// </summary>
        MagicTower = 9,
    }

} 

