
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Rain.Core
{
public sealed partial class DeployFormationConfig : Luban.BeanBase
{
    public DeployFormationConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["val"].IsString) { throw new SerializationException(); }  Val = _buf["val"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
    }

    public static DeployFormationConfig DeserializeDeployFormationConfig(JSONNode _buf)
    {
        return new DeployFormationConfig(_buf);
    }

    /// <summary>
    /// 阵型 ID（主键）
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 阵型名称
    /// </summary>
    public readonly string Val;
    public readonly string Name;
   
    public const int __ID__ = 1669643084;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "val:" + Val + ","
        + "name:" + Name + ","
        + "}";
    }
}
}

