
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Rain.Core
{ 
    /// <summary>
    /// 道具类型
    /// </summary>
    public enum ItemType
    {
        /// <summary>
        /// 资源
        /// </summary>
        Res = 0,
        /// <summary>
        /// 加速
        /// </summary>
        Speed = 1,
        /// <summary>
        /// 增益
        /// </summary>
        Buff = 2,
        /// <summary>
        /// 装备
        /// </summary>
        Equip = 3,
        /// <summary>
        /// 其他
        /// </summary>
        Other = 4,
    }

} 

