
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Rain.Core
{ 
    /// <summary>
    /// 资源类型
    /// </summary>
    public enum ResType
    {
        /// <summary>
        /// 食物
        /// </summary>
        Food = 0,
        /// <summary>
        /// 木材
        /// </summary>
        Wood = 1,
        /// <summary>
        /// 金币
        /// </summary>
        Gold = 2,
        /// <summary>
        /// 魔法书
        /// </summary>
        Book = 3,
        /// <summary>
        /// 矿石
        /// </summary>
        Ore = 4,
    }

} 

