
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Rain.Core
{
public partial class Tables
{
    /// <summary>
    /// 设置
    /// </summary>
    public TbGameSetting TbGameSetting {get; }
    /// <summary>
    /// 设置
    /// </summary>
    public TbSLGSetting TbSLGSetting {get; }
    /// <summary>
    /// 图文混合
    /// </summary>
    public TbImageTextMix TbImageTextMix {get; }
    /// <summary>
    /// 科技
    /// </summary>
    public TbTech TbTech {get; }
    /// <summary>
    /// 科技种类
    /// </summary>
    public TbTechCategory TbTechCategory {get; }
    /// <summary>
    /// 城镇建筑
    /// </summary>
    public TbCityBuilding TbCityBuilding {get; }
    /// <summary>
    /// 建筑层级
    /// </summary>
    public TbCityBuildingLevel TbCityBuildingLevel {get; }
    /// <summary>
    /// 建筑槽位
    /// </summary>
    public TbCityBuildingSlot TbCityBuildingSlot {get; }
    /// <summary>
    /// 道具
    /// </summary>
    public TbItem TbItem {get; }
    /// <summary>
    /// 单位
    /// </summary>
    public TbUnit TbUnit {get; }
    /// <summary>
    /// 阵型
    /// </summary>
    public TbDeployFormation TbDeployFormation {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbGameSetting = new TbGameSetting(loader("tbgamesetting"));
        TbSLGSetting = new TbSLGSetting(loader("tbslgsetting"));
        TbImageTextMix = new TbImageTextMix(loader("tbimagetextmix"));
        TbTech = new TbTech(loader("tbtech"));
        TbTechCategory = new TbTechCategory(loader("tbtechcategory"));
        TbCityBuilding = new TbCityBuilding(loader("tbcitybuilding"));
        TbCityBuildingLevel = new TbCityBuildingLevel(loader("tbcitybuildinglevel"));
        TbCityBuildingSlot = new TbCityBuildingSlot(loader("tbcitybuildingslot"));
        TbItem = new TbItem(loader("tbitem"));
        TbUnit = new TbUnit(loader("tbunit"));
        TbDeployFormation = new TbDeployFormation(loader("tbdeployformation"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbGameSetting.ResolveRef(this);
        TbSLGSetting.ResolveRef(this);
        TbImageTextMix.ResolveRef(this);
        TbTech.ResolveRef(this);
        TbTechCategory.ResolveRef(this);
        TbCityBuilding.ResolveRef(this);
        TbCityBuildingLevel.ResolveRef(this);
        TbCityBuildingSlot.ResolveRef(this);
        TbItem.ResolveRef(this);
        TbUnit.ResolveRef(this);
        TbDeployFormation.ResolveRef(this);
    }
}

}
