
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Rain.Core
{
public partial class Tables
{
    /// <summary>
    /// 设置
    /// </summary>
    public TbGameSetting TbGameSetting {get; }
    /// <summary>
    /// 设置
    /// </summary>
    public TbSLGSetting TbSLGSetting {get; }
    /// <summary>
    /// 图文混合
    /// </summary>
    public TbImageTextMix TbImageTextMix {get; }
    /// <summary>
    /// 单位
    /// </summary>
    public TbUnit TbUnit {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbGameSetting = new TbGameSetting(loader("tbgamesetting"));
        TbSLGSetting = new TbSLGSetting(loader("tbslgsetting"));
        TbImageTextMix = new TbImageTextMix(loader("tbimagetextmix"));
        TbUnit = new TbUnit(loader("tbunit"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbGameSetting.ResolveRef(this);
        TbSLGSetting.ResolveRef(this);
        TbImageTextMix.ResolveRef(this);
        TbUnit.ResolveRef(this);
    }
}

}
