
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Rain.Core
{
/// <summary>
/// 城镇建筑
/// </summary>
public partial class TbCityBuilding
{
    private readonly System.Collections.Generic.Dictionary<CityBuildingType, CityBuildingConfig> _dataMap;
    private readonly System.Collections.Generic.List<CityBuildingConfig> _dataList;
    
    public TbCityBuilding(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<CityBuildingType, CityBuildingConfig>();
        _dataList = new System.Collections.Generic.List<CityBuildingConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CityBuildingConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Rain.Core.CityBuildingConfig.DeserializeCityBuildingConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.BuildingID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<CityBuildingType, CityBuildingConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<CityBuildingConfig> DataList => _dataList;

    public CityBuildingConfig GetOrDefault(CityBuildingType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CityBuildingConfig Get(CityBuildingType key) => _dataMap[key];
    public CityBuildingConfig this[CityBuildingType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

