
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Rain.Core
{
/// <summary>
/// 建筑槽位
/// </summary>
public partial class TbCityBuildingSlot
{
    private readonly System.Collections.Generic.Dictionary<int, BuildingSlotConfig> _dataMap;
    private readonly System.Collections.Generic.List<BuildingSlotConfig> _dataList;
    
    public TbCityBuildingSlot(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BuildingSlotConfig>();
        _dataList = new System.Collections.Generic.List<BuildingSlotConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BuildingSlotConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Rain.Core.BuildingSlotConfig.DeserializeBuildingSlotConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.SlotID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BuildingSlotConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<BuildingSlotConfig> DataList => _dataList;

    public BuildingSlotConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BuildingSlotConfig Get(int key) => _dataMap[key];
    public BuildingSlotConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

