
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Rain.Core
{
/// <summary>
/// 建筑层级
/// </summary>
public partial class TbCityBuildingLevel
{
    private readonly System.Collections.Generic.Dictionary<string, CityBuildingLevelConfig> _dataMap;
    private readonly System.Collections.Generic.List<CityBuildingLevelConfig> _dataList;
    
    public TbCityBuildingLevel(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, CityBuildingLevelConfig>();
        _dataList = new System.Collections.Generic.List<CityBuildingLevelConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CityBuildingLevelConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Rain.Core.CityBuildingLevelConfig.DeserializeCityBuildingLevelConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, CityBuildingLevelConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<CityBuildingLevelConfig> DataList => _dataList;

    public CityBuildingLevelConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CityBuildingLevelConfig Get(string key) => _dataMap[key];
    public CityBuildingLevelConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

