
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Rain.Core
{
/// <summary>
/// 阵型
/// </summary>
public partial class TbDeployFormation
{
    private readonly System.Collections.Generic.Dictionary<int, DeployFormationConfig> _dataMap;
    private readonly System.Collections.Generic.List<DeployFormationConfig> _dataList;
    
    public TbDeployFormation(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DeployFormationConfig>();
        _dataList = new System.Collections.Generic.List<DeployFormationConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DeployFormationConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Rain.Core.DeployFormationConfig.DeserializeDeployFormationConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DeployFormationConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<DeployFormationConfig> DataList => _dataList;

    public DeployFormationConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DeployFormationConfig Get(int key) => _dataMap[key];
    public DeployFormationConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

