
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Rain.Core
{
/// <summary>
/// 科技
/// </summary>
public partial class TbTech
{
    private readonly System.Collections.Generic.Dictionary<string, TechConfig> _dataMap;
    private readonly System.Collections.Generic.List<TechConfig> _dataList;
    
    public TbTech(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, TechConfig>();
        _dataList = new System.Collections.Generic.List<TechConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            TechConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Rain.Core.TechConfig.DeserializeTechConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.TechID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, TechConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<TechConfig> DataList => _dataList;

    public TechConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TechConfig Get(string key) => _dataMap[key];
    public TechConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

