
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Rain.Core
{
/// <summary>
/// 科技种类
/// </summary>
public partial class TbTechCategory
{
    private readonly System.Collections.Generic.Dictionary<TechCategory, TechCategoryConfig> _dataMap;
    private readonly System.Collections.Generic.List<TechCategoryConfig> _dataList;
    
    public TbTechCategory(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<TechCategory, TechCategoryConfig>();
        _dataList = new System.Collections.Generic.List<TechCategoryConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            TechCategoryConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Rain.Core.TechCategoryConfig.DeserializeTechCategoryConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<TechCategory, TechCategoryConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<TechCategoryConfig> DataList => _dataList;

    public TechCategoryConfig GetOrDefault(TechCategory key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TechCategoryConfig Get(TechCategory key) => _dataMap[key];
    public TechCategoryConfig this[TechCategory key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

