
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Rain.Core
{
/// <summary>
/// 单位
/// </summary>
public partial class TbUnit
{
    private readonly System.Collections.Generic.Dictionary<int, UnitConfig> _dataMap;
    private readonly System.Collections.Generic.List<UnitConfig> _dataList;
    
    public TbUnit(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, UnitConfig>();
        _dataList = new System.Collections.Generic.List<UnitConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            UnitConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Rain.Core.UnitConfig.DeserializeUnitConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, UnitConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<UnitConfig> DataList => _dataList;

    public UnitConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UnitConfig Get(int key) => _dataMap[key];
    public UnitConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

