
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Rain.Core
{ 
    /// <summary>
    /// 科技分类
    /// </summary>
    public enum TechCategory
    {
        /// <summary>
        /// 战斗
        /// </summary>
        Battle = 0,
        /// <summary>
        /// 资源
        /// </summary>
        Resource = 1,
        /// <summary>
        /// 发展
        /// </summary>
        Development = 2,
    }

} 

