
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Rain.Core
{
public sealed partial class TechCategoryConfig : Luban.BeanBase
{
    public TechCategoryConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = (TechCategory)_buf["ID"].AsInt; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Icon"].IsString) { throw new SerializationException(); }  Icon = _buf["Icon"]; }
    }

    public static TechCategoryConfig DeserializeTechCategoryConfig(JSONNode _buf)
    {
        return new TechCategoryConfig(_buf);
    }

    public readonly TechCategory ID;
    public readonly string Name;
    public readonly string Icon;
   
    public const int __ID__ = 365855286;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Icon:" + Icon + ","
        + "}";
    }
}
}

