
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Rain.Core
{ 
    /// <summary>
    /// 单位类型
    /// </summary>
    public enum UnitType
    {
        /// <summary>
        /// 假人
        /// </summary>
        Dummy = -1,
        /// <summary>
        /// 玩家
        /// </summary>
        Player = 0,
        /// <summary>
        /// 步兵
        /// </summary>
        Infantry = 1,
        /// <summary>
        /// 弓箭手
        /// </summary>
        Archer = 2,
        /// <summary>
        /// 骑士
        /// </summary>
        Cavalry = 3,
        /// <summary>
        /// 魔法师
        /// </summary>
        Mage = 4,
    }

} 

