#Scene配置
#必填#
#[Scene]
#可选#
# [Scene].comment: 场景注释
scenes:
    Launcher:
        comment: 启动场景
    MainCity:
        comment: 主城 
    WorldMap:
        comment: 世界地图
    TD:
        comment: 塔防场景
    RTSUnitTest:
        comment: RTS单位测试场景
    RTSBattle:
        comment: RTS战斗场景
    RTSUnitDummyTest:
        comment: RTS单位测试

