#层级配置 每个层级单位之间额间隔默认为400，也就是说order为1的层级从400开始，与order为2的层级中间间隔400个sortingOrder可以使用，[comment]为注释
#考虑到canvas的sortingOrder最大只能到32767，order的上限不能超过32767/400也就是80稍多一点，为保证增加默认间隔不需要修改order，建议最大order不超过40
layer:
    NormalLayer:
        comment: 普通UI
        order: 0
    MenuLayer:
        comment: 游戏菜单UI
        order: 5
    DialogLayer:
        comment: 弹窗UI
        order: 10
    TipsLayer:
        comment: 提示UI
        order: 20
    GuideLayer:
        comment: 引导UI
        order: 25
    PreventLayer:
        comment: 阻挡点击UI
        order: 27
    CursorLayer:
        comment: 光标特效
        order: 28

#View配置
#必填#
#[key]为prefab同名，默认也与脚本同名
#[comment]为注释，调试时会用到
#可选#
#[layer]为layer配置字段，用来调整canvas的sortingOrder 默认NormalLayer
#[hasBg]为背景图是否接受射线 默认true
#[bgColor]背景颜色默认透明  默认#00000000
#[bgClose]点击背景是否关闭 默认false
#[showMethod]显示动画 对标ViewShowMethod字段 默认normal
view:
    DebugView:
        comment: 调试弹窗
        layer: NormalLayer
    BlockView:
        comment: 奖励弹窗
        layer: DialogLayer
        hasBg: true
        bgColor: "#000000B0"
    TopView:
        comment: 资源栏
        layer: DialogLayer
        hasBg: false
    LoadingView:
        comment: loading
        layer: DialogLayer
    ExampleView:
        comment: 示例UI
        layer: DialogLayer
        bgColor: "#000000B0"
        showMethod: pop
        bgClose: true
    TipsView:
        comment: 提示弹窗UI
        layer: TipsLayer
        hasBg: false
    ImageTextMixView:
        comment: 图文混合
        bgColor: "#000000B0"
        bgClose: true
    HUDView:
        comment: 战场计时数据
        layer: TipsLayer
        hasBg: false
    RecruitView:
        comment: 招募
        layer: DialogLayer
        bgColor: "#000000B0"
    LoadSceneView:
        comment: 读取页面
    CursorEffectView:
        comment: 光标特效
        layer: CursorLayer
        hasBg: false
    EscView:
        comment: 暂停游戏菜单
        layer: TipsLayer
        bgColor: "#000000B0"
    SettingView:
        comment: 设置
        layer: TipsLayer
        bgColor: "#000000B0"
    CityInfoView:
        comment: 城镇信息
        layer: DialogLayer
        bgColor: "#000000B0"
        showMethod: pop
    BattleVictoryView:
        comment: 战斗胜利
        layer: DialogLayer
        bgColor: "#000000B0"
    BattleDefeatView:
        comment: 战斗失败
        layer: DialogLayer
        bgColor: "#000000B0"
    UIControlDemoView:
        comment: UI组件示例
        layer: NormalLayer
        bgColor: "#000000ff"
    DemoView:
        comment: UI示例
        layer: NormalLayer
        bgColor: "#000000ff"
    CardMatchGameView:
        comment: 翻卡牌
        layer: NormalLayer
        bgColor: "#FFFFFFFF"
    CountDownView:
        comment: 倒计时
        layer: TipsLayer
        bgColor: "#FFFFFFFF"
        
