
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.common
{
public sealed partial class GameSetting : Luban.BeanBase
{
    public GameSetting(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["val"].IsString) { throw new SerializationException(); }  Val = _buf["val"]; }
    }

    public static GameSetting DeserializeGameSetting(JSONNode _buf)
    {
        return new common.GameSetting(_buf);
    }

    public readonly string ID;
    public readonly string Val;
   
    public const int __ID__ = -355506597;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "val:" + Val + ","
        + "}";
    }
}
}

